name: "Unit Testing"

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build environment
        run: make up
      - name: run tests
        run: make test
